<?php
/**
 * Created by PhpStorm.
 * User: lewis
 * Date: 30/06/2018
 * Time: 23:31
 */

namespace Colourspace\Framework\Profiles;

use Colourspace\Framework\Profile;
use Colourspace\Container;
use Colourspace\Framework\Track;
use Colourspace\Framework\User;
use Colourspace\Framework\Session;

class Tracks extends Profile
{

    /**
     * @var Track
     */

    protected $track;

    /**
     * @var User
     */

    protected $user;

    /**
     * @var Session
     */

    protected $session;

    /**
     * Tracks constructor.
     * @param array $classes
     * @throws \Error
     */

    public function __construct(array $classes = [])
    {

        parent::__construct(
            [
                [
                    "Colourspace\\Framework\\", "Track"
                ],
                [
                    "Colourspace\\Framework\\", "User"
                ]
            ]
        );

        $this->track = $this->class("Track");
        $this->user = $this->class( "User");
        $this->session = Container::get('application')->session;
    }

    /**
     * @return null|void
     * @throws \Error
     */

    public function create()
    {

        if( $this->session->isLoggedIn() == false )
            $this->objects = null;
        else
        {

            $tracks = $this->track->user( $this->session->userid() );

            if( $tracks->isEmpty() )
                $tracks->objects = null;

            $this->objects = $tracks->toArray();
        }

        parent::create(); // TODO: Change the autogenerated stub
    }
}