<?php
/**
 * Created by PhpStorm.
 * User: lewis
 * Date: 05/07/2018
 * Time: 20:41
 */

namespace Colourspace\Framework\Controllers;


class Upload extends DefaultController
{

    public function process(string $type, $data)
    {

        parent::process($type, $data); // TODO: Change the autogenerated stub
    }

    public function authentication(string $type, $data)
    {

        return parent::authentication($type, $data);
    }
}